# Generated by Django 4.2.6 on 2024-01-06 23:15

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.UUIDField(default=uuid.UUID('11d2c510-8781-4888-995e-7c718b224faa'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
    ]
