# Generated by Django 4.2.6 on 2024-01-06 23:16

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.UUIDField(default=uuid.UUID('9d7b89de-3d7c-48ab-86af-d3d7236f6c8a'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
    ]
