# Generated by Django 4.2.6 on 2024-01-06 23:17

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.UUIDField(default=uuid.UUID('e2c6bc7c-caa8-4cdf-8bc0-63e8e226ad07'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
    ]
