# Generated by Django 5.0.1 on 2024-02-17 10:35

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='id',
            field=models.UUIDField(default=uuid.UUID('142ec16d-b961-45f1-be8a-6182070de4a0'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
    ]
