# Generated by Django 4.2 on 2024-02-22 23:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0004_favourite'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Favourite',
        ),
    ]
