# Generated by Django 4.2 on 2024-02-23 01:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0008_alter_contact_group'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='contact_picture',
            field=models.URLField(blank=True, null=True),
        ),
    ]
